// export const BASE_URL = "http://18.207.239.155:8080/v1/";
export const BASE_URL = "http://localhost:8080/v1/";
export const HEALTH_URL = "api/health/";
export const GET_ALL_BOOK_URL = "api/book?page=0&size=10";
export const CREATE_BOOK_URL = "api/book";
export const BOOK_URL = "api/book";
export const URL_REGISTER = "api/user";
export const CATEGORY_URL = "api/category";
export const LOGIN_URL = "api/auth/login";
export const USER_URL = "api/user/";
export const GET_ALL_USERS_URL = "api/user";
export const UPLOAD_IMAGEN_BOOK_URL = "api/book-image";
export const CREATE_INVOICE_URL = "api/invoice";